import { StyleSheet } from "react-native";

export const globalStyle = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "#FFF",
    },
    backImage: {
        width: "100%",
        height: "100%",
        position: "absolute",
        top: 0,
        resizeMode: "cover",
    },
    button: {
        backgroundColor: '#640e8c',
        height: 58,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 40,
      },
      buttonCS: {
        backgroundColor: "#806d8f",
        height: 50,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: 'center',
        marginTop: 5,
      },
      buttonEditRecipe: {
        backgroundColor: "#806d8f",
        borderRadius: 20,
        justifyContent: "center",
        alignItems: 'center',
        marginTop: 10,
        marginLeft: 10,
        marginRight: 10,
      },
    input: {
        backgroundColor: "#FAF6FB",
        height: 58,
        marginBottom: 20,
        fontSize: 16,
        borderRadius: 10,
        padding: 12,
    },
    title: {
        fontSize: 36,
        fontWeight: 'bold',
        color: "purple",
        alignSelf: "center",
        paddingBottom: 24,
    },
    titleNote: {
      fontSize: 20,
      fontWeight: 'bold',
      alignSelf: 'flex-start', 
      padding: 5,
      color: '#4d066f',
    },
    form: {
        flex: 1,
        justifyContent: 'center',
        marginHorizontal: 30,
        marginTop: "10%",
      },
      whiteSheetSU: {
        width: "100%",
        height: "63%",
        position: 'absolute',
        bottom: 0,
        backgroundColor: '#f5e4f5',
        borderRadius: 60,
        marginBottom: "30%",
      },
      errorText: {
        color: "#e74c3c", 
        fontWeight: 'bold', 
        fontSize: 10,
        alignSelf: "center",
        marginBottom: -20,
      },
      inputTitle: {
        fontSize: 25,
        fontWeight: 'bold',
        backgroundColor: "#c5b2e0",
        borderRadius: 15,
        marginLeft: 10,
        width: "85%",
      },
      titleRecipe: {
        fontSize: 36,
        fontWeight: 'bold',
        color: '#c887f3',
        marginLeft: 10,
      },
      inputCuerpo: {
        fontSize: 16,
        backgroundColor: "#dbcfed",
        borderRadius: 15,
        marginTop: 5,
        marginBottom: 25,
        height: 48,
      },
      nota: {
        marginTop: 15, 
        flexDirection: 'row', 
      },
      buttonAN: {
        backgroundColor: '#9b73ab',
        borderColor: '#8e61a1',
        borderWidth: 3,
        margin: 15,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: 'center',
        height: 55,
      },
      buttonAddDose: {
      backgroundColor: '#a182b6',
      borderColor: '#916ba1',
      borderWidth: 3,
      margin: 10,
      borderRadius: 20,
      justifyContent: "center",
      alignItems: 'center',
      },
      containerNotes: {
        backgroundColor: 'rgba(224, 195, 236, 0.7)',
        marginTop: 5,
        borderColor: '#e0c3ec',
        borderWidth: 2,
        borderRadius: 5,
      },
      buttonSU: {
        backgroundColor: "#806d8f",
        height: 50,
        width: "45%",
        borderRadius: 20,
        justifyContent: "center",
        alignItems: 'center',
        marginTop: 5,
      },
      buttonDEL: {
        backgroundColor: "#675d6b",
        height: 50,
        width: "45%",
        borderRadius: 20,
        justifyContent: "center",
        alignItems: 'center',
        marginTop: 5,
        marginRight: 35,
      },
      sheetRecipe: {
        margin: 20,
        backgroundColor: 'rgba(161, 130, 182, 0.4)',
        borderRadius: 5,
      },
});